### ISSUE TITLE
Please update the README!

### ISSUE THREAD

**Issue by vxld100** [evesdropper/luasnip-latex-snippets.nvim#3]
I just wasted half an hour battling with strange errors whenever I wanted to write anything in a .tex file. Then I read the file listing the snippets and saw that the `vimtex` plugin is needed for most things to work. For the love of god, please mention this in your README, and put `vimtex` as a dependency in the code snippet showing how to install this plugin. Not only is this not visible at first glance (and it should be), but the file which contains this crucial information isn't even marked as documentation!

**Comment by evesdropper** [comment]
fixed, apologies for not adding that in the README

I'd also appreciate it if you dropped the attitude.

**Comment by vxld100** [comment]
I know. I apologize. But it's quite infuriating.
