### ISSUE TITLE
bmat expands before I can set condition

### ISSUE THREAD

**Issue by v0ry** [evesdropper/luasnip-latex-snippets.nvim#4]

**Comment by evesdropper** [comment]
Hi, is it possible for you to provide some video evidence - I tried replicating it myself and I didn't see any issues.

**Comment by v0ry** [comment]
Uploading Bildschirmaufnahme 2024-02-11 um 11.05.58 PM.mov…

**Comment by evesdropper** [comment]
Thanks for the clarification and dotfiles. From the video it looks like you aren't using my snippets; a look at [your dotfiles](https://github.com/v0ry/dotfiles.public/blob/main/nvim/lua/user/luasnip-latex-snippets.lua) also confirms this.
