### ISSUE TITLE
Auto snippet matches alpha and \alpha

### ISSUE THREAD

**Issue by mmiddlezong** [evesdropper/luasnip-latex-snippets.nvim#5]
Hey, just wanted to say I really appreciate this plugin. In math mode, typing `alpha` turns into `\alpha` and typing `\alpha` turns into `\\alpha`. Is this intended? I would expect typing `\alpha` to not trigger the snippet and return `\alpha` (unaffected). This issue is not noticed with `\angle`, for example.

**Comment by evesdropper** [comment]
Ah, this is because there's no regex pattern to prevent this snippet from triggering again when prefaced by a backslash. This should be a pretty quick fix; it should be updated now.

**Comment by mmiddlezong** [comment]
Thank you for the quick response and fix!

**Comment by mmiddlezong** [comment]
A similar issue exists with `\sqrt`, and I've implemented a similar fix in my fork of this repository but wanted to let you know.

**Comment by evesdropper** [comment]
Essentially the issue lies with snippets which have some trigger `trig` but produce something like `\trig[optional stuff]`; therefore I found a more efficient fix - just need to put a check that context.trig is contained within the command. This also eliminates the need for the backslash flag.
