### ISSUE TITLE
Matrix snippet, `a` not valid

### ISSUE THREAD

**Issue by Libadoxon** [evesdropper/luasnip-latex-snippets.nvim#8]
I'm relatively new to latex, so I might be missing something here but when I try, `pmat3x3a` it generates:
```tex
\begin{pmatrix}[cc|c]
   &  & \\
   &  & \\
   &  & \\
\end{pmatrix}
```
But isn't `[cc|c]` only valid for arrays? When I try the above with some random numbers no line will be drawn and `[cc|c]` will be displayed as text

**Comment by evesdropper** [comment]
Looking at [snippets.md](https://github.com/evesdropper/luasnip-latex-snippets.nvim/blob/main/snippets.md#useful-math-dynamic-snippets), note that the augment requires [this fix](https://tex.stackexchange.com/a/2238) to create augmented matrices.

**Comment by Libadoxon** [comment]
Ah I think I understand now, I have seen the link but thought it was for something else because it shows to wrong answer when clicking on it and you have to scroll down to see the command to extend the matrices. I don't know if you can fix this but I think at least a bit of clarification in the docs would be nice. Anyways everything works as expected now, thx for the quick reply
